name: Nuget Package Deploy
on:
  push:
    branches:
      - master # Default release branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pack Nuget Package
        run: dotnet pack --configuration Release
      - name: Push package to GitHub Package Registry
        run: dotnet nuget push **/*.nupkg 
             --api-key ${{ secrets.action_nuget_package }} 
             --source https://nuget.pkg.github.com/ZyshchykMaksim/index.json 
             --no-symbols true



    